In [1]:
import numpy as np

In [2]:
X = np.array([[1,2,2], [10,20,10],[1,21,2],[0,9 , 0]])
Y = np.array([[1,2,10], [5,10,0],[1,0,1]])

In [3]:
a = np.sum(np.square(X),axis=1,keepdims=1)
b = np.ones((1,Y.shape[0]))
c = a.dot(b)
a = np.ones((X.shape[0],1))
b = np.sum(np.square(Y),axis=1,keepdims=1).T
c += a.dot(b)
c -= 2*X.dot(Y.T)
c = np.sqrt(c)

In [4]:
print(c)

[[ 8.          9.16515139  2.23606798]
 [20.1246118  15.         23.70653918]
 [20.61552813 11.87434209 21.02379604]
 [12.24744871  5.09901951  9.11043358]]


In [19]:
indices = np.argpartition(c, 1, axis=1)[:, :2]
print(indices)

[[0 2]
 [1 0]
 [1 0]
 [2 0]]


In [20]:
a = [1,0,1,0,2]
len(set(a))

3

In [21]:
l = np.array([ [ [1,2] , [2,3 ] , [3,4 ] ] , [ [2,2] , [2,6 ] , [10,10 ] ] ])

array([[1, 2],
       [2, 3],
       [3, 4]])